/* soapPullPointSubscriptionBindingProxy.cpp
   Generated by gSOAP 2.8.135 for event.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapPullPointSubscriptionBindingProxy.h"

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	PullPointSubscriptionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(const PullPointSubscriptionBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	PullPointSubscriptionBindingProxy_init(_soap->imode, _soap->omode);
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	PullPointSubscriptionBindingProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	PullPointSubscriptionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	PullPointSubscriptionBindingProxy_init(iomode, iomode);
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	PullPointSubscriptionBindingProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	PullPointSubscriptionBindingProxy_init(imode, omode);
}

PullPointSubscriptionBindingProxy::~PullPointSubscriptionBindingProxy()
{	if (this->soap_own)
	{	PullPointSubscriptionBindingProxy::destroy();
		soap_free(this->soap);
	}
}

void PullPointSubscriptionBindingProxy::PullPointSubscriptionBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL },
        { "wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL },
        { "wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL },
        { "wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL },
        { "wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL },
        { "EventBinding", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL },
        { "EventBinding2", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL },
        { "tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL },
        { "EventBinding3", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL },
        { "EventBinding4", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL },
        { "EventBinding5", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL },
        { "EventBinding6", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL },
        { "EventBinding7", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL },
        { "EventBinding8", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL },
        { "wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this->soap, namespaces);
}

PullPointSubscriptionBindingProxy *PullPointSubscriptionBindingProxy::copy()
{	PullPointSubscriptionBindingProxy *dup = SOAP_NEW_UNMANAGED(PullPointSubscriptionBindingProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

PullPointSubscriptionBindingProxy& PullPointSubscriptionBindingProxy::operator=(const PullPointSubscriptionBindingProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void PullPointSubscriptionBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void PullPointSubscriptionBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	PullPointSubscriptionBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void PullPointSubscriptionBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void PullPointSubscriptionBindingProxy::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{
	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
}

::SOAP_ENV__Header *PullPointSubscriptionBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *PullPointSubscriptionBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *PullPointSubscriptionBindingProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *PullPointSubscriptionBindingProxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *PullPointSubscriptionBindingProxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int PullPointSubscriptionBindingProxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int PullPointSubscriptionBindingProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void PullPointSubscriptionBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void PullPointSubscriptionBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *PullPointSubscriptionBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int PullPointSubscriptionBindingProxy::send_PullMessages(const char *soap_endpoint_url, const char *soap_action, _tev__PullMessages *tev__PullMessages)
{
	struct __EventBinding__PullMessages soap_tmp___EventBinding__PullMessages;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesRequest";
	soap_tmp___EventBinding__PullMessages.tev__PullMessages = tev__PullMessages;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___EventBinding__PullMessages(soap, &soap_tmp___EventBinding__PullMessages);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___EventBinding__PullMessages(soap, &soap_tmp___EventBinding__PullMessages, "-EventBinding:PullMessages", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___EventBinding__PullMessages(soap, &soap_tmp___EventBinding__PullMessages, "-EventBinding:PullMessages", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int PullPointSubscriptionBindingProxy::recv_PullMessages(_tev__PullMessagesResponse &tev__PullMessagesResponse)
{
	tev__PullMessagesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tev__PullMessagesResponse.soap_get(soap, "tev:PullMessagesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PullPointSubscriptionBindingProxy::send_Seek(const char *soap_endpoint_url, const char *soap_action, _tev__Seek *tev__Seek)
{
	struct __EventBinding__Seek soap_tmp___EventBinding__Seek;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/SeekRequest";
	soap_tmp___EventBinding__Seek.tev__Seek = tev__Seek;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___EventBinding__Seek(soap, &soap_tmp___EventBinding__Seek);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___EventBinding__Seek(soap, &soap_tmp___EventBinding__Seek, "-EventBinding:Seek", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___EventBinding__Seek(soap, &soap_tmp___EventBinding__Seek, "-EventBinding:Seek", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int PullPointSubscriptionBindingProxy::recv_Seek(_tev__SeekResponse &tev__SeekResponse)
{
	tev__SeekResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tev__SeekResponse.soap_get(soap, "tev:SeekResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PullPointSubscriptionBindingProxy::send_SetSynchronizationPoint(const char *soap_endpoint_url, const char *soap_action, _tev__SetSynchronizationPoint *tev__SetSynchronizationPoint)
{
	struct __EventBinding__SetSynchronizationPoint soap_tmp___EventBinding__SetSynchronizationPoint;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/SetSynchronizationPointRequest";
	soap_tmp___EventBinding__SetSynchronizationPoint.tev__SetSynchronizationPoint = tev__SetSynchronizationPoint;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___EventBinding__SetSynchronizationPoint(soap, &soap_tmp___EventBinding__SetSynchronizationPoint);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___EventBinding__SetSynchronizationPoint(soap, &soap_tmp___EventBinding__SetSynchronizationPoint, "-EventBinding:SetSynchronizationPoint", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___EventBinding__SetSynchronizationPoint(soap, &soap_tmp___EventBinding__SetSynchronizationPoint, "-EventBinding:SetSynchronizationPoint", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int PullPointSubscriptionBindingProxy::recv_SetSynchronizationPoint(_tev__SetSynchronizationPointResponse &tev__SetSynchronizationPointResponse)
{
	tev__SetSynchronizationPointResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	tev__SetSynchronizationPointResponse.soap_get(soap, "tev:SetSynchronizationPointResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int PullPointSubscriptionBindingProxy::send_Unsubscribe(const char *soap_endpoint_url, const char *soap_action, _wsnt__Unsubscribe *wsnt__Unsubscribe)
{
	struct __EventBinding__Unsubscribe soap_tmp___EventBinding__Unsubscribe;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_action == NULL)
		soap_action = "http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest";
	soap_tmp___EventBinding__Unsubscribe.wsnt__Unsubscribe = wsnt__Unsubscribe;
	soap_begin(soap);
	soap_set_version(soap, 2); /* use SOAP1.2 */
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___EventBinding__Unsubscribe(soap, &soap_tmp___EventBinding__Unsubscribe);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___EventBinding__Unsubscribe(soap, &soap_tmp___EventBinding__Unsubscribe, "-EventBinding:Unsubscribe", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___EventBinding__Unsubscribe(soap, &soap_tmp___EventBinding__Unsubscribe, "-EventBinding:Unsubscribe", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int PullPointSubscriptionBindingProxy::recv_Unsubscribe(_wsnt__UnsubscribeResponse &wsnt__UnsubscribeResponse)
{
	wsnt__UnsubscribeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wsnt__UnsubscribeResponse.soap_get(soap, "wsnt:UnsubscribeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
