/* soapEventBindingService.cpp
   Generated by gSOAP 2.8.135 for event.h

gSOAP XML Web services tools
Copyright (C) 2000,2024, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapEventBindingService.h"

EventBindingService::EventBindingService()
{	this->soap = soap_new();
	this->soap_own = true;
	EventBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

EventBindingService::EventBindingService(const EventBindingService& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
}

EventBindingService::EventBindingService(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	EventBindingService_init(_soap->imode, _soap->omode);
}

EventBindingService::EventBindingService(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	EventBindingService_init(iomode, iomode);
}

EventBindingService::EventBindingService(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	EventBindingService_init(imode, omode);
}

EventBindingService::~EventBindingService()
{	if (this->soap_own)
	{	EventBindingService::destroy();
		soap_free(this->soap);
	}
}

void EventBindingService::EventBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL },
        { "SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL },
        { "wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL },
        { "wsrfbf", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL },
        { "wstop", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL },
        { "wsrfr", "http://docs.oasis-open.org/wsrf/r-2", NULL, NULL },
        { "EventBinding", "http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding", NULL, NULL },
        { "EventBinding2", "http://www.onvif.org/ver10/events/wsdl/EventBinding", NULL, NULL },
        { "tev", "http://www.onvif.org/ver10/events/wsdl", NULL, NULL },
        { "EventBinding3", "http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding", NULL, NULL },
        { "EventBinding4", "http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding", NULL, NULL },
        { "EventBinding5", "http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding", NULL, NULL },
        { "EventBinding6", "http://www.onvif.org/ver10/events/wsdl/PullPointBinding", NULL, NULL },
        { "EventBinding7", "http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding", NULL, NULL },
        { "EventBinding8", "http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding", NULL, NULL },
        { "wsnt", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this->soap, namespaces);
}

void EventBindingService::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void EventBindingService::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	EventBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
EventBindingService *EventBindingService::copy()
{	EventBindingService *dup = SOAP_NEW_UNMANAGED(EventBindingService);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}
#endif

EventBindingService& EventBindingService::operator=(const EventBindingService& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
	}
	return *this;
}

int EventBindingService::soap_close_socket()
{	return soap_closesock(this->soap);
}

int EventBindingService::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

int EventBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this->soap, string, detailXML);
}

int EventBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

int EventBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this->soap, string, detailXML);
}

int EventBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this->soap, subcodeQName, string, detailXML);
}

void EventBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void EventBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *EventBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

void EventBindingService::soap_noheader()
{	this->soap->header = NULL;
}

void EventBindingService::soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{
	::soap_header(this->soap);
	this->soap->header->wsa5__MessageID = wsa5__MessageID;
	this->soap->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->soap->header->wsa5__From = wsa5__From;
	this->soap->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->soap->header->wsa5__FaultTo = wsa5__FaultTo;
	this->soap->header->wsa5__To = wsa5__To;
	this->soap->header->wsa5__Action = wsa5__Action;
	this->soap->header->chan__ChannelInstance = chan__ChannelInstance;
}

::SOAP_ENV__Header *EventBindingService::soap_header()
{	return this->soap->header;
}

#ifndef WITH_NOIO
int EventBindingService::run(int port, int backlog)
{	if (!soap_valid_socket(this->soap->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->soap->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->soap->errnum == 0) // timeout?
				this->soap->error = SOAP_OK;
			break;
		}
		if (this->serve())
			break;
		this->destroy();
	}
	return this->soap->error;
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int EventBindingService::ssl_run(int port, int backlog)
{	if (!soap_valid_socket(this->soap->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->soap->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->soap->errnum == 0) // timeout?
				this->soap->error = SOAP_OK;
			break;
		}
		if (this->ssl_accept() || this->serve())
			break;
		this->destroy();
	}
	return this->soap->error;
}
#endif

SOAP_SOCKET EventBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this->soap, host, port, backlog);
}

SOAP_SOCKET EventBindingService::accept()
{	return soap_accept(this->soap);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int EventBindingService::ssl_accept()
{	return soap_ssl_accept(this->soap);
}
#endif
#endif

int EventBindingService::serve()
{
#ifndef WITH_FASTCGI
	this->soap->keep_alive = this->soap->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (this->soap->keep_alive > 0 && this->soap->max_keep_alive > 0)
			this->soap->keep_alive--;
#endif
		if (soap_begin_serve(this->soap))
		{	if (this->soap->error >= SOAP_STOP)
				continue;
			return this->soap->error;
		}
		if ((dispatch() || (this->soap->fserveloop && this->soap->fserveloop(this->soap))) && this->soap->error && this->soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this->soap);
#else
			return soap_send_fault(this->soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(this->soap);
		soap_end(this->soap);
	} while (1);
#else
	} while (this->soap->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___EventBinding2__GetServiceCapabilities(struct soap*, EventBindingService*);
static int serve___EventBinding2__CreatePullPointSubscription(struct soap*, EventBindingService*);
static int serve___EventBinding2__GetEventProperties(struct soap*, EventBindingService*);
static int serve___EventBinding2__AddEventBroker(struct soap*, EventBindingService*);
static int serve___EventBinding2__DeleteEventBroker(struct soap*, EventBindingService*);
static int serve___EventBinding2__GetEventBrokers(struct soap*, EventBindingService*);

int EventBindingService::dispatch()
{	return dispatch(this->soap);
}

int EventBindingService::dispatch(struct soap* soap)
{
	EventBindingService_init(soap->imode, soap->omode);
	(void)soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "tev:GetServiceCapabilities"))
		return serve___EventBinding2__GetServiceCapabilities(soap, this);
	if (!soap_match_tag(soap, soap->tag, "tev:CreatePullPointSubscription"))
		return serve___EventBinding2__CreatePullPointSubscription(soap, this);
	if (!soap_match_tag(soap, soap->tag, "tev:GetEventProperties"))
		return serve___EventBinding2__GetEventProperties(soap, this);
	if (!soap_match_tag(soap, soap->tag, "tev:AddEventBroker"))
		return serve___EventBinding2__AddEventBroker(soap, this);
	if (!soap_match_tag(soap, soap->tag, "tev:DeleteEventBroker"))
		return serve___EventBinding2__DeleteEventBroker(soap, this);
	if (!soap_match_tag(soap, soap->tag, "tev:GetEventBrokers"))
		return serve___EventBinding2__GetEventBrokers(soap, this);
	return soap->error = SOAP_NO_METHOD;
}

static int serve___EventBinding2__GetServiceCapabilities(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__GetServiceCapabilities soap_tmp___EventBinding2__GetServiceCapabilities;
	_tev__GetServiceCapabilitiesResponse tev__GetServiceCapabilitiesResponse;
	tev__GetServiceCapabilitiesResponse.soap_default(soap);
	soap_default___EventBinding2__GetServiceCapabilities(soap, &soap_tmp___EventBinding2__GetServiceCapabilities);
	if (!soap_get___EventBinding2__GetServiceCapabilities(soap, &soap_tmp___EventBinding2__GetServiceCapabilities, "-EventBinding2:GetServiceCapabilities", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetServiceCapabilities(soap_tmp___EventBinding2__GetServiceCapabilities.tev__GetServiceCapabilities, tev__GetServiceCapabilitiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__GetServiceCapabilitiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__GetServiceCapabilitiesResponse.soap_put(soap, "tev:GetServiceCapabilitiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__GetServiceCapabilitiesResponse.soap_put(soap, "tev:GetServiceCapabilitiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___EventBinding2__CreatePullPointSubscription(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__CreatePullPointSubscription soap_tmp___EventBinding2__CreatePullPointSubscription;
	_tev__CreatePullPointSubscriptionResponse tev__CreatePullPointSubscriptionResponse;
	tev__CreatePullPointSubscriptionResponse.soap_default(soap);
	soap_default___EventBinding2__CreatePullPointSubscription(soap, &soap_tmp___EventBinding2__CreatePullPointSubscription);
	if (!soap_get___EventBinding2__CreatePullPointSubscription(soap, &soap_tmp___EventBinding2__CreatePullPointSubscription, "-EventBinding2:CreatePullPointSubscription", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->CreatePullPointSubscription(soap_tmp___EventBinding2__CreatePullPointSubscription.tev__CreatePullPointSubscription, tev__CreatePullPointSubscriptionResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__CreatePullPointSubscriptionResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__CreatePullPointSubscriptionResponse.soap_put(soap, "tev:CreatePullPointSubscriptionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__CreatePullPointSubscriptionResponse.soap_put(soap, "tev:CreatePullPointSubscriptionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___EventBinding2__GetEventProperties(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__GetEventProperties soap_tmp___EventBinding2__GetEventProperties;
	_tev__GetEventPropertiesResponse tev__GetEventPropertiesResponse;
	tev__GetEventPropertiesResponse.soap_default(soap);
	soap_default___EventBinding2__GetEventProperties(soap, &soap_tmp___EventBinding2__GetEventProperties);
	if (!soap_get___EventBinding2__GetEventProperties(soap, &soap_tmp___EventBinding2__GetEventProperties, "-EventBinding2:GetEventProperties", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetEventProperties(soap_tmp___EventBinding2__GetEventProperties.tev__GetEventProperties, tev__GetEventPropertiesResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__GetEventPropertiesResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__GetEventPropertiesResponse.soap_put(soap, "tev:GetEventPropertiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__GetEventPropertiesResponse.soap_put(soap, "tev:GetEventPropertiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___EventBinding2__AddEventBroker(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__AddEventBroker soap_tmp___EventBinding2__AddEventBroker;
	_tev__AddEventBrokerResponse tev__AddEventBrokerResponse;
	tev__AddEventBrokerResponse.soap_default(soap);
	soap_default___EventBinding2__AddEventBroker(soap, &soap_tmp___EventBinding2__AddEventBroker);
	if (!soap_get___EventBinding2__AddEventBroker(soap, &soap_tmp___EventBinding2__AddEventBroker, "-EventBinding2:AddEventBroker", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->AddEventBroker(soap_tmp___EventBinding2__AddEventBroker.tev__AddEventBroker, tev__AddEventBrokerResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__AddEventBrokerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__AddEventBrokerResponse.soap_put(soap, "tev:AddEventBrokerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__AddEventBrokerResponse.soap_put(soap, "tev:AddEventBrokerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___EventBinding2__DeleteEventBroker(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__DeleteEventBroker soap_tmp___EventBinding2__DeleteEventBroker;
	_tev__DeleteEventBrokerResponse tev__DeleteEventBrokerResponse;
	tev__DeleteEventBrokerResponse.soap_default(soap);
	soap_default___EventBinding2__DeleteEventBroker(soap, &soap_tmp___EventBinding2__DeleteEventBroker);
	if (!soap_get___EventBinding2__DeleteEventBroker(soap, &soap_tmp___EventBinding2__DeleteEventBroker, "-EventBinding2:DeleteEventBroker", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->DeleteEventBroker(soap_tmp___EventBinding2__DeleteEventBroker.tev__DeleteEventBroker, tev__DeleteEventBrokerResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__DeleteEventBrokerResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__DeleteEventBrokerResponse.soap_put(soap, "tev:DeleteEventBrokerResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__DeleteEventBrokerResponse.soap_put(soap, "tev:DeleteEventBrokerResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___EventBinding2__GetEventBrokers(struct soap *soap, EventBindingService *service)
{	struct __EventBinding2__GetEventBrokers soap_tmp___EventBinding2__GetEventBrokers;
	_tev__GetEventBrokersResponse tev__GetEventBrokersResponse;
	tev__GetEventBrokersResponse.soap_default(soap);
	soap_default___EventBinding2__GetEventBrokers(soap, &soap_tmp___EventBinding2__GetEventBrokers);
	if (!soap_get___EventBinding2__GetEventBrokers(soap, &soap_tmp___EventBinding2__GetEventBrokers, "-EventBinding2:GetEventBrokers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = service->GetEventBrokers(soap_tmp___EventBinding2__GetEventBrokers.tev__GetEventBrokers, tev__GetEventBrokersResponse);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	tev__GetEventBrokersResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tev__GetEventBrokersResponse.soap_put(soap, "tev:GetEventBrokersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tev__GetEventBrokersResponse.soap_put(soap, "tev:GetEventBrokersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
